title: Mohammed Mubashir M
logo: poto.jpg
theme: jekyll-theme-minimal
description: >-
  Data Analyst | Power BI | Excel | SQL | Tableau |
  Helping businesses make data-driven decisions with clear, compelling dashboards.
